### ISSUE TITLE
Automated browser compatibility testing

### ISSUE THREAD

**Issue by pluma** [pluma0/fynx#5]
We're currently supporting IE8+, Firefox and Chrome. Safari, Opera, Android browsers, Mobile Safari, etc should probably work too.

It'd be nice if we automated the browser testing (at least when pushing to CI). Since testling seems to be dead, I'm looking for a substitute. Maybe SauceLabs?

**Comment by StevenLangbroek** [comment]
+1 for Saucelabs, we're using it here. If you want I can add Karma + Saucelabs launcher (easiest setup).
